# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('difficulty', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('initial_registers', jsonfield.fields.JSONField(blank=True, default=None, null=True)),
                ('expected_registers', jsonfield.fields.JSONField()),
                ('code_prefix', models.TextField(blank=True, default='', null=True)),
                ('code_postfix', models.TextField(blank=True, default='', null=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembler_execution.Stage')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('solved', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembler_execution.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
