# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 14:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assembler_execution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='assembler_execution.Stage'),
        ),
        migrations.AlterField(
            model_name='tasksolution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_solutions', to='assembler_execution.Task'),
        ),
        migrations.AlterField(
            model_name='tasksolution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_solutions', to=settings.AUTH_USER_MODEL),
        ),
    ]
