# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembler_execution', '0003_auto_20170316_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hint',
            field=models.TextField(blank=True, default=''),
        ),
    ]
