# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 14:29
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assembler_execution', '0006_auto_20170321_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='registers',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
